### ISSUE TITLE
Release for nxrm 3.38.0-01

### ISSUE THREAD

**Issue by jfabales** [sonatype-nexus-community/nexus-repository-cpan#22]
* **What are you trying to do?**
Upgrade to nxrm 3.38.0-01

* **What feature or behavior is this required for?**
Would it be possible to get a release compatible with nxrm 3.38.0-01?
We've upgraded to this version and found that nxrm wouldn't start because of the existence of a cpan proxy repository

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by ekarlso** [comment]
Second this!

**Comment by christophvw** [comment]
I have the same problem

**Comment by christophvw** [comment]
https://github.com/sonatype-nexus-community/nexus-repository-cpan/pull/23
