### ISSUE TITLE
only proxy repo available

### ISSUE THREAD

**Issue by yenda23** [sonatype-nexus-community/nexus-repository-cpan#7]
Hi,
when I install CPAN repository (must use nexus v >3.19) I can see only proxy repo, hosted repo is not supported?

**Comment by joedragons** [comment]
Not implemented, correct.  See https://github.com/sonatype-nexus-community/nexus-repository-cpan/blob/master/docs/CPAN_USER_DOCUMENTATION.md (only proxy listed).

**Comment by yenda23** [comment]
I see, thx
