### ISSUE TITLE
nexus repository version 3.25

### ISSUE THREAD

**Issue by lapfrank12** [sonatype-nexus-community/nexus-repository-cpan#9]
Hi,

I just updated to nexus repository version 3.25.03 from 3.22.0. The CPAN plugin was working in 3.22, but in 3.25, it seems to prevent the repository from starting up. Is there any plans to update this open source plugin or to make it native to Nexus?

Thanks!

**Comment by bhamail** [comment]
Resolved by updating to latest Nexus Repository Manager release. see: #14
Please holler if you find problems running the latest version with Nexus 3.29.2-02.
